name: clean_architecture_tdd_flutter_template
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  http: ^1.1.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  lottie: ^2.6.0
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  provider: ^6.0.5
  iconly: ^1.0.1
  dio: ^5.3.3
  uuid: ^4.2.1
  flutter_svg: ^2.0.9
  mobile_scanner: ^3.5.2
  qr_flutter: ^4.1.0

  file_picker: ^6.1.1

  image_picker: ^1.0.4
  flutter_nfc_kit: ^3.4.1
  timeline_tile: ^2.0.0
  latlng: ^1.0.0
  geolocator: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  mocktail: ^1.0.1
  bloc_test: ^9.1.4

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/lotties/
    - assets/vectors/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Black.ttf
          weight: 900
        - asset: assets/fonts/inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter-Thin.ttf
          weight: 200
        - asset: assets/fonts/inter/Inter-ExtraLight.ttf
          weight: 100
